"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

export default function TermsPage() {
  const sections = [
    {
      id: "1",
      title: "The Service",
      content: "Fitnivo is an AI-powered fitness and wellness assistant. We provide workout plan generation, meal planning suggestions, mindfulness audio, and health tracking tools. These services are provided \"as-is\" and are intended for general motivational and educational purposes only."
    },
    {
      id: "2",
      title: "Eligibility",
      content: "You must be at least 13 years old to use Fitnivo. By using the app, you represent that you have the legal capacity to enter into a binding agreement."
    },
    {
      id: "3",
      title: "Subscriptions & Payments",
      content: (
        <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
          <p>Fitnivo offers a \"Pro\" subscription via RevenueCat and the Google Play Store.</p>
          <ul style={{ listStyleType: "disc", paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "8px" }}>
            <li><strong>Billing:</strong> Payments are handled by Google Play. You agree to their terms for processing.</li>
            <li><strong>Access:</strong> Access to Pro features is granted only during an active subscription period. Features may change over time.</li>
            <li><strong>Automatic Renewal:</strong> Subscriptions renew until cancelled via your Play Store account.</li>
            <li><strong>Refunds:</strong> Refund requests are governed by Google Play Store policies and are not handled directly by Fitnivo.</li>
          </ul>
        </div>
      )
    },
    {
      id: "4",
      title: "Medical & Health Disclaimer",
      content: (
        <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
          <p style={{ fontWeight: "700", color: "#FF2D55" }}>FITNIVO IS NOT A MEDICAL DEVICE AND DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT.</p>
          <ul style={{ listStyleType: "disc", paddingLeft: "20px", display: "flex", flexDirection: "column", gap: "8px" }}>
            <li><strong>Consult Your Doctor:</strong> Always seek the advice of a physician before starting any new exercise or diet program, especially if you have pre-existing conditions.</li>
            <li><strong>Risk Acknowledgment:</strong> Use of the app and following generated plans is at your own risk. Fitnivo is not responsible for any injuries or health issues resulting from use.</li>
          </ul>
        </div>
      )
    },
    {
      id: "5",
      title: "AI Disclaimer (Fitbuu 🐻)",
      content: "Coaching interactions and plans are generated by Artificial Intelligence. While we strive for high-quality guidance, AI content can be inaccurate, incomplete, or out-of-date. Always use common sense and professional judgment when following AI suggestions."
    },
    {
      id: "6",
      title: "Intellectual Property",
      content: "All content including but not limited to the Fitnivo logo, \"Fitbuu\" mascot, UI design, audio tracks, and proprietary algorithms, are the exclusive property of Fitnivo."
    },
    {
      id: "7",
      title: "User Conduct",
      content: "You agree not to attempt to reverse-engineer the application, scrape data, or use the AI features to generate harmful, illegal, or malicious content."
    },
    {
      id: "8",
      title: "Limitation of Liability",
      content: "To the maximum extent permitted by law, Fitnivo shall not be liable for any indirect, incidental, or consequential damages resulting from your use or inability to use the service."
    },
    {
      id: "9",
      title: "Termination & Account Deletion",
      content: (
        <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
          <p>We reserve the right to suspend or terminate your account at our sole discretion, without notice, for conduct that violates these Terms or is harmful to other users.</p>
          <p><strong>User Right:</strong> You may stop using the app and request account deletion at any time via the settings menu.</p>
        </div>
      )
    },
    {
      id: "10",
      title: "Governing Law",
      content: "These Terms shall be governed by and interpreted in accordance with the laws of India, without regard to conflict of law principles."
    },
    {
      id: "11",
      title: "Account Responsibility",
      content: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."
    },
    {
      id: "12",
      title: "Service Availability",
      content: "We do not guarantee that the app will be uninterrupted, error-free, or available at all times. Features may be modified, suspended, or discontinued at any time without prior notice."
    },
    {
      id: "13",
      title: "User-Generated Content",
      content: "You retain ownership of the data you input into the app (such as workout logs, journal entries, and nutrition data). By using Fitnivo, you grant us a limited license to process this data solely for providing and improving our services."
    },
    {
      id: "14",
      title: "Changes to Terms",
      content: "We may update these Terms from time to time. Continued use of the app after changes constitutes acceptance of the updated Terms."
    },
    {
      id: "15",
      title: "Contact & Support",
      content: (
        <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
          <p>If you have questions about this Privacy Policy or your data rights, please contact us at:</p>
          <a href="mailto:support@fitnivo.in" style={{ color: "var(--accent-primary)", fontWeight: "600", textDecoration: "none" }}>support@fitnivo.in</a>
        </div>
      )
    }
  ];

  return (
    <main style={{ background: "#050505", minHeight: "100vh" }}>
      <Navbar />
      
      <section style={{ paddingTop: "clamp(120px, 15vw, 180px)", paddingBottom: "clamp(60px, 8vw, 100px)" }}>
        <div className="container" style={{ maxWidth: "800px" }}>
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            style={{ textAlign: "center" }}
          >
            <h1 style={{ 
              fontSize: "clamp(36px, 8vw, 72px)", 
              fontWeight: "900", 
              letterSpacing: "-0.04em", 
              lineHeight: "1", 
              marginBottom: "24px" 
            }}>
              Terms of <span style={{ color: "#00F2FF" }}>Service</span>
            </h1>
            <p style={{ color: "rgba(255,255,255,0.4)", fontSize: "14px", marginBottom: "clamp(40px, 10vw, 80px)" }}>
              Last Updated: April 2026
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.2 }}
            style={{ display: "flex", flexDirection: "column", gap: "clamp(40px, 8vw, 60px)" }}
          >
            <p style={{ fontSize: "clamp(16px, 3vw, 20px)", lineHeight: "1.6", color: "rgba(255,255,255,0.8)", fontWeight: "400", textAlign: "center" }}>
              Welcome to Fitnivo. These Terms cover your use of the Fitnivo mobile app. 
              By using our services, you agree to these Terms. 
              If you do not agree, please do not use the application.
            </p>

            {sections.map((section) => (
              <div key={section.id} style={{ borderTop: "1px solid rgba(255,255,255,0.05)", paddingTop: "32px" }}>
                <h2 style={{ 
                  fontSize: "11px", 
                  fontWeight: "800", 
                  color: "#00F2FF", 
                  letterSpacing: "0.2em", 
                  textTransform: "uppercase",
                  marginBottom: "16px"
                }}>
                  {section.id}. {section.title}
                </h2>
                <div style={{ 
                  fontSize: "15px", 
                  lineHeight: "1.8", 
                  color: "rgba(255,255,255,0.5)",
                  fontWeight: "400"
                }}>
                  {section.content}
                </div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
